serverFiles:
  alerting_rules.yml:
    groups:
      - name: test
        rules:
          - alert: InstanceDown
            expr: up{job="node-exporter"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: Instance is down
              description: "The instance {{ $labels.instance }} is not reachable."

server:
  service:
    type: LoadBalancer
    port: 80
nodeExporter:
  enabled: true
